import React from 'react';
import { BrowserRouter as Router, Routes, Route, Link } from 'react-router-dom';
import StockData from './StockData';
import './App.css';

function App() {
    return (
        <Router>
            <div className="App">
                <header className="App-header">
                    <h1>Stock-Prediction Hacker</h1>
                    <h2>See the stock market data of major companies and the predictions of an AI.</h2>

                    <nav>
                        <ul className='stock-list'>
                            <li className="stock-item"><Link to="/StockData/NVDA" className="stock-link">NVIDIA FUTURE</Link></li>
                            <li className="stock-item"><Link to="/StockData/AAPL" className="stock-link">Apple FUTURE</Link></li>
                            <li className="stock-item"><Link to="/StockData/AMZN" className="stock-link">Amazon FUTURE</Link></li>
                            <li className="stock-item"><Link to="/StockData/MSFT" className="stock-link">Microsoft FUTURE</Link></li>
                            <li className="stock-item"><Link to="/StockData/GOOGL" className="stock-link">Google FUTURE</Link></li>
                        </ul>
                    </nav>

                    <p className="disclaimer">"We are not responsible for any financial losses, etc. The data generated by the AI may be incorrect."</p>
                </header>

                {/* Footer Section */}
                <footer className="footer">
                    <div className="legal-info">
                        <p>&copy; 2024 Your Company. All rights reserved.</p>
                        <p>Terms of Use | Privacy Policy</p>
                    </div>
                    <div className="social-media">
                        <p>Follow us on Instagram:</p>
                        <a
                            href="https://www.instagram.com/monu.kumar565"
                            target="_blank"
                            rel="noopener noreferrer"
                        >
                            <img
                                src="/path/to/instagram-icon.png" // Replace with actual Instagram logo image path
                                alt="Instagram"
                                className="instagram-icon"
                            />
                            @monu.kumar565
                        </a>
                    </div>
                </footer>
                {/* End of Footer Section */}

                <Routes>
                    <Route path="/StockData/:stockSymbol" element={<StockData />} />
                </Routes>
            </div>
        </Router>
    );
}

export default App;
